### ISSUE TITLE
Update code which references the marketplace image as opposed to an uploaded VHD image

### ISSUE THREAD

**Issue by SI-BenHodges** [christofvg/AzureVDC#1]
Hey Christo,

Just been reading through your helpful posts all around pfsense and hub-to-spoke networks which is something i've been working on recently and wondered if you could upload a version of the code which references the netgate pfsense image as opposed to the VHD?

I know you mentioned about using this over VHD too and i agree, just thinking it could be good to include this on git.

Ben

**Comment by christofvg** [comment]
Hi Ben,

If you would like to use a pfSense from the marketplace (which is covered by support), then I would suggest to deploy using the portal. If you would like to use ARM templates, to enable redeployment, you could begin creating a deployment from the marketplace and in the last step, choose 'Download a template for automation'. You can adjust it to your needs, store it in source control and deploy using CI/CD if you want.

![image](https://user-images.githubusercontent.com/22281419/74747307-0a87c300-5267-11ea-8cbd-302251df2245.png)

When I have a bit more time, I'll add an ARM template in this repo later on.

I hope this helps!

Kind regards,
Christof Van Geendertaelen

**Comment by SI-BenHodges** [comment]
Hi Christof,

Thanks, this is actually what i do already. I just meant updating your template which builds the loadbalancers, nics, pfsense va's etc to use the pfsense image as opposed to the vhd image. That template only deploys a pfsense va.

cheers
Ben

**Comment by christofvg** [comment]
Hi Ben,

Maybe a good idea to create another branch to use pfsense images instead of the vhd images. I'll create the branch ASAP!

Thanks for the nice suggestion! :-)

Cheers,
Christof
